from django.urls import path
from .views import PostListView, PostDetailView, ExploreView, ProfileView, ManagePostView, PostEditView, PostDeleteView, CommentDeleteView, CommentEditView, EditProfileView, AddFollower, RemoveFollower, AddFollowing, RemoveFollowing, ToggleLike, UserSearch, ListFollowers, ListFollowing, ToggleCommentLike, CommentReplyView, PostNotification, FollowNotification, RemoveNotification, PostLikesView, CommentLikesView, SettingsView, deactivate_account, delete_account, SharePostView, ListThreads, CreateThread, ThreadView, CreateMessage, ThreadNotification

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('explore/', ExploreView.as_view(), name='explore'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/manage-post/', ManagePostView.as_view(), name='manage-post'),
    path('post/edit/<int:pk>/', PostEditView.as_view(), name='post-edit'),
    path('post/delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('post/<int:post_pk>/comment/edit/<int:pk>/', CommentEditView.as_view(), name='comment-edit'),
    path('profile/edit/<int:pk>/', EditProfileView.as_view(), name='edit-profile'),
    path('profile/<int:pk>/followers/add/', AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove/', RemoveFollower.as_view(), name='remove-follower'),
    path('profile/<int:pk>/following/add/', AddFollowing.as_view(), name='add-following'),
    path('profile/<int:pk>/following/remove/', RemoveFollowing.as_view(), name='remove-following'),
    path('post/<int:pk>/like/', ToggleLike.as_view(), name='toggle-like'),
    path('search/', UserSearch.as_view(), name='profile-search'),
    path('profile/<int:pk>/followers/', ListFollowers.as_view(), name='followers-list'),
    path('profile/<int:pk>/following/', ListFollowing.as_view(), name='following-list'),
    path('post/<int:post_pk>/comment/<int:pk>/like/', ToggleCommentLike.as_view(), name='comment-like'),
    path('post/<int:post_pk>/comment/<int:pk>/reply/', CommentReplyView.as_view(), name='comment-reply'),
    path('notification/<int:notification_pk>/post/<int:post_pk>/', PostNotification.as_view(), name='post-notification'),
    path('notification/<int:notification_pk>/profile/<int:profile_pk>/', FollowNotification.as_view(), name='follow-notification'),
    path('notification/<int:notification_pk>/thread/<int:thread_pk>/', ThreadNotification.as_view(), name='thread-notification'),
    path('notification/delete/<int:notification_pk>/', RemoveNotification.as_view(), name='notification-delete'),
    path('post/<int:post_pk>/likes/', PostLikesView.as_view(), name='post-likes'),
    path('post/<int:post_pk>/comment/<int:comment_pk>/likes/', CommentLikesView.as_view(), name='comment-likes'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('settings/deactivate/', deactivate_account, name='deactivate-account'),
    path('settings/delete/', delete_account, name='delete-account'),
    path('post/<int:pk>/share/', SharePostView.as_view(), name='share-post'),
    path('inbox/', ListThreads.as_view(), name='inbox'),
    path('inbox/create-thread/', CreateThread.as_view(), name='create-thread'),
    path('inbox/<int:pk>/', ThreadView.as_view(), name='thread'),
    path('inbox/<int:pk>/create-message/', CreateMessage.as_view(), name='create-message'),
]