# Generated by Django 5.1.1 on 2024-09-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_image_postimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='caption',
        ),
    ]
