# Generated by Django 5.1.1 on 2024-09-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(blank=True, default='banners/banner.webp', upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile-pictures/profile.jpg', upload_to='profile-pictures'),
        ),
    ]
