# Generated by Django 5.1.1 on 2024-09-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_rename_images_postimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='social.postimages'),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
