# Generated by Django 5.1.1 on 2024-09-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_remove_post_image_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(to='social.postimages'),
        ),
    ]
