# Generated by Django 5.1.1 on 2024-09-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_remove_post_image_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
